# @package _group_
data_root_dir: /data/liulingzhuo/lama/lama/places_standard_dataset/
out_root_dir: /data/liulingzhuo/lama/lama/experiments/
tb_dir: /data/liulingzhuo/lama/lama/tb_logs/
pretrained_models: /data/liulingzhuo/lama/lama/
